services:
  sigmarulegen:
    image: ghcr.io/05t3/sigmarulegen:${VERSION} # GHCR IMAGE
#    image: oste/sigmarulegen:1.0.0  # DOCKERHUB IMAGE
    container_name: sigmarulegen
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}" # DEFINE PORT in the .env file 
    restart: unless-stopped
