services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}" # uses PORT from .env
    restart: unless-stopped
    container_name: sigmarulegen
    command: npm run start # If production
    # command: npm run dev # If development