services:
  sigmarulegen:
    image: ghcr.io/05t3/sigmarulegen:1.0.1
    container_name: sigmarulegen
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}" # uses PORT from .env
    restart: unless-stopped
