name: Snyk Container Vulnerability Scan

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to Docker Hub and GHCR using VERSION file"]
    types:
      - completed

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  snyk-scan:
    name: Scan Remote Container Images with Snyk
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Pull and scan GHCR image with Snyk
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: docker pull ghcr.io/${{ steps.image.outputs.repo_lower }}:${{ steps.version.outputs.version }}
          args: >
            --file=Dockerfile
            --sarif-file-output=snyk-ghcr.sarif
            --remote

      - name: Upload GHCR scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-ghcr.sarif

      - name: Pull and scan DockerHub image with Snyk
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: docker pull oste/${{ steps.image.outputs.image_name }}:${{ steps.version.outputs.version }}
          args: >
            --file=Dockerfile
            --sarif-file-output=snyk-dockerhub.sarif
            --remote

      - name: Upload DockerHub scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-dockerhub.sarif
